<?php

function lang_all()
{
    return array(
        'ar' => array(
            'dashboard' => 'الرئيسية',
            'subscribers' => 'المشتركين',
            'sas' => 'المشتركين',
            'offline_data' => 'بيانات أوف لاين',
            'subscriptions' => 'الحركات',
            'movements' => 'الحركات',
            'activate_new' => 'تفعيل اشتراك جديد',
            'sort_order' => 'التسلسل (الأقل يظهر أول)',
            'drag_hint' => 'اسحب الصف لترتيب الباقات',
            'reconnect_wa' => 'قطع الاتصال وإعادة الربط',
            'language' => 'اللغة',
            'login_hint' => 'أدخل كلمة مرور الإدارة للمتابعة',
            'choose_lang' => 'اختر اللغة',
            'admin_panel' => 'لوحة الإدارة',
            'debts' => 'التسديد والديون',
            'reports' => 'التقارير',
            'plans' => 'الباقات',
            'settings' => 'الإعدادات',
            'backup' => 'نسخ احتياطي',
            'logout' => 'خروج',
            'menu' => 'القائمة',
            'save' => 'حفظ',
            'search' => 'بحث',
            'delete' => 'حذف',
            'edit' => 'تعديل',
            'add_subscriber' => 'إضافة مشترك',
            'activate' => 'تفعيل',
            'give_test' => 'إضافة 1 يوم',
            'confirm_give_test' => 'إضافة يوم واحد على الساس عبر النقاط التشجيعية؟',
            'sas_reward_points' => 'نقاط SAS التشجيعية',
            'pay_send' => 'تسديد + رسالة',
            'pay_only' => 'تسديد فقط',
            'remind' => 'تذكير',
            'name' => 'الاسم',
            'phone' => 'الهاتف',
            'address' => 'العنوان',
            'notes' => 'ملاحظات',
            'package' => 'الباقة',
            'from_date' => 'من تاريخ',
            'to_date' => 'إلى تاريخ',
            'message_note' => 'ملاحظة تُرسل مع واتساب',
            'send_whatsapp' => 'إرسال واتساب',
            'create_invoice' => 'إنشاء فاتورة/دين',
            'pay_mode' => 'طريقة الدفع',
            'pay_cash' => 'نقد',
            'pay_credit' => 'آجل',
            'pay_cash_hint' => 'يستلم المبلغ الآن — بدون دين',
            'pay_credit_hint' => 'يسجّل دين على المشترك',
            'site_name' => 'اسم الموقع',
            'gateway_url' => 'رابط بوابة واتساب',
            'gateway_key' => 'مفتاح البوابة',
            'whatsapp_on' => 'تفعيل واتساب',
            'backup_now' => 'تحميل نسخة احتياطية',
            'restore' => 'استرجاع نسخة',
            'sell_price' => 'سعر البيع',
            'cost_price' => 'سعر الجملة',
            'all_subscribers' => 'كل المشتركين',
            'online' => 'واصل',
            'offline' => 'غير واصل',
            'online_hint' => 'اشتراك مفعّل',
            'offline_hint' => 'انتهى اشتراكه',
            'online_mix' => 'نقد {cash} · آجل {credit}',
            'pick_contact' => 'من الدليل',
            'contacts_unsupported' => 'اختيار جهات الاتصال يحتاج كروم أندرويد مع HTTPS. اكتب الرقم يدوياً.',
            'debts_total' => 'الديون',
            'collected' => 'المستلم',
            'profit' => 'الربح',
            'confirm_delete' => 'حذف المشترك؟',
            'saved' => 'تم الحفظ',
            'login' => 'تسجيل الدخول',
            'password' => 'كلمة المرور',
            'movements_list' => 'قائمة الحركات',
            'settings_general' => 'عام',
            'settings_whatsapp' => 'واتساب',
            'settings_sas' => 'ربط SAS',
            'settings_templates' => 'القوالب',
            'export' => 'تصدير',
            'import' => 'استيراد',
            'import_export' => 'استيراد وتصدير',
            'print' => 'طباعة',
            'days_left' => 'الأيام المتبقية',
            'remind_debt' => 'تذكير دين',
            'pay_debt' => 'تسديد',
            'show_all' => 'عرض الكل',
            'templates' => 'القوالب',
            'msg_debt_remind' => 'رسالة تذكير الدين',
            'msg_payment_ok' => 'رسالة تأكيد التسديد',
            'msg_debt_created' => 'رسالة إضافة دين',
            'msg_activation' => 'رسالة التفعيل',
            'partial_pay' => 'مبلغ التسديد',
            'remaining_after' => 'المتبقي',
            'debt_notes' => 'ملاحظات الدين',
            'debt_type_month' => 'شهر اشتراك',
            'debt_type_item' => 'غرض / حاجة',
            'debt_type_month_rent' => 'شهر اشتراك + إيجار',
            'pay_debts' => 'تسديد ديون',
            'status_active' => 'نشط',
            'status_inactive' => 'غير نشط',
            'pay_full' => 'تسديد كل المبلغ',
            'pay_partial_mode' => 'تسديد جزء من المبلغ',
            'pay_choose_debt' => 'اختر الدين المراد تسديده',
            'sub_type' => 'نوع الاشتراك',
            'change_sub_type' => 'تغيير نوع الاشتراك',
            'bulk_activate' => 'تفعيل المحددين',
            'operations' => 'العمليات',
            'status_active_short' => 'فعال',
            'status_expired_short' => 'منتهي',
            'status_left_short' => 'متروك',
            'confirm_activate' => 'تأكيد تفعيل المشترك؟',
            'quick_activate' => 'تفعيل سريع',
            'show_details' => 'إظهار التفاصيل',
            'hide_details' => 'إخفاء التفاصيل',
            'advanced' => 'متقدم',
            'activate_amount' => 'المبلغ',
            'current_package' => 'الباقة الحالية',
            'send_message' => 'إرسال رسالة',
            'send_old_debts_detail' => 'إرسال الديون القديمة بالتفصيل',
            'send_wa_notice' => 'إرسال إشعار عبر واتساب',
            'include_old_debts' => 'تضمين الديون القديمة',
            'old_debts' => 'الديون القديمة',
            'no_old_debts' => 'لا توجد ديون قديمة',
            'this_activation' => 'هذا التفعيل',
            'after_activate' => 'بعد التفعيل',
            'grand_total' => 'الإجمالي',
            'pay_this' => 'تسديد هذا',
            'pay_this_amount' => 'تسديد هذا المبلغ',
            'pay_all_debts' => 'تسديد كل الديون',
            'collapse_menu' => 'طي القائمة',
            'collected_chart' => 'استلام هذا الشهر',
            'activation_sales' => 'مبيعات التفعيل',
            'sales_short' => 'مبيعات',
            'activations_month' => 'تفعيلات هذا الشهر',
            'datetime_card' => 'التاريخ والوقت',
            'capital' => 'رأس المال',
            'capital_hint' => 'تكلفة هذا الشهر',
            'collected_year' => 'الاستلام خلال السنة',
            'add_debts_tab' => 'إضافة ديون',
            'debts_list_tab' => 'قائمة الديون',
            'debts_need_pay' => 'ديون بحاجة لتسديد',
            'no_debts_now' => 'لا توجد ديون حالياً',
            'messages' => 'الرسائل',
            'clear_data' => 'مسح كل البيانات',
            'clear_logs' => 'مسح اللوك',
            'clear_offline' => 'مسح الديون والاشتراكات المحلية',
            'confirm_clear_logs' => 'سيتم حذف كل حركات اللوك. متأكد؟',
            'confirm_clear_offline' => 'سيتم حذف الديون والاشتراكات المحلية وسجل الرسائل. كاش SAS يبقى. متأكد؟',
            'select_all' => 'تحديد الكل',
            'delete_selected' => 'حذف المحدد',
            'expire' => 'إنهاء',
            'days_unit' => 'يوم',
            'filter_days' => 'الأيام المتبقية أقل من أو تساوي',
            'send_filtered' => 'إرسال للنتائج',
            'send_selected' => 'إرسال للمحددين',
            'select_none' => 'إلغاء التحديد',
            'msg_mode_debt' => 'تذكير الديون',
            'msg_mode_days' => 'قرب انتهاء الاشتراك',
            'opening_debts' => 'ديون قديمة',
            'add_debt_line' => 'إضافة سطر',
            'remove_debt_line' => 'حذف السطر',
            'msg_status' => 'الرسالة',
            'msg_history' => 'سجل الرسائل',
            'retry_send' => 'إعادة المحاولة',
            'confirm_clear' => 'سيتم حذف كل المشتركين والحركات والديون. متأكد؟',
            'choose_month' => 'اختر الشهر',
            'show' => 'عرض',
            'custom_text' => 'نص مخصص',
            'add_debt_btn' => 'إضافة دين',
            'send_notice' => 'إرسال إشعار إلى المشترك',
        ),
        'en' => array(
            'dashboard' => 'Dashboard',
            'subscribers' => 'Subscribers',
            'sas' => 'Subscribers',
            'offline_data' => 'Offline data',
            'subscriptions' => 'Movements',
            'movements' => 'Movements',
            'activate_new' => 'Activate new subscription',
            'sort_order' => 'Order (lower shows first)',
            'drag_hint' => 'Drag rows to reorder packages',
            'reconnect_wa' => 'Disconnect & reconnect',
            'language' => 'Language',
            'login_hint' => 'Enter admin password to continue',
            'choose_lang' => 'Choose language',
            'admin_panel' => 'Admin Panel',
            'debts' => 'Payments & Debts',
            'reports' => 'Reports',
            'plans' => 'Packages',
            'settings' => 'Settings',
            'backup' => 'Backup',
            'logout' => 'Logout',
            'menu' => 'Menu',
            'save' => 'Save',
            'search' => 'Search',
            'delete' => 'Delete',
            'edit' => 'Edit',
            'add_subscriber' => 'Add Subscriber',
            'activate' => 'Activate',
            'give_test' => '+ 1 day',
            'confirm_give_test' => 'Add one day on SAS using reward points?',
            'sas_reward_points' => 'SAS reward points',
            'pay_send' => 'Pay + Message',
            'pay_only' => 'Pay only',
            'remind' => 'Remind',
            'name' => 'Name',
            'phone' => 'Phone',
            'address' => 'Address',
            'notes' => 'Notes',
            'package' => 'Package',
            'from_date' => 'From',
            'to_date' => 'To',
            'message_note' => 'Note for WhatsApp',
            'send_whatsapp' => 'Send WhatsApp',
            'create_invoice' => 'Create invoice/debt',
            'pay_mode' => 'Payment mode',
            'pay_cash' => 'Cash',
            'pay_credit' => 'Credit',
            'pay_cash_hint' => 'Paid now — no debt',
            'pay_credit_hint' => 'Record as unpaid debt',
            'site_name' => 'Site name',
            'gateway_url' => 'WhatsApp gateway URL',
            'gateway_key' => 'Gateway key',
            'whatsapp_on' => 'Enable WhatsApp',
            'backup_now' => 'Download backup',
            'restore' => 'Restore backup',
            'sell_price' => 'Sell price',
            'cost_price' => 'Wholesale cost',
            'all_subscribers' => 'All subscribers',
            'online' => 'Online',
            'offline' => 'Offline',
            'online_hint' => 'Active subscription',
            'offline_hint' => 'Subscription ended',
            'online_mix' => 'Cash {cash} · Credit {credit}',
            'pick_contact' => 'Contacts',
            'contacts_unsupported' => 'Contact picker needs Chrome Android with HTTPS. Enter the number manually.',
            'debts_total' => 'Debts',
            'collected' => 'Collected',
            'profit' => 'Profit',
            'confirm_delete' => 'Delete subscriber?',
            'saved' => 'Saved',
            'login' => 'Login',
            'password' => 'Password',
            'movements_list' => 'Movements list',
            'settings_general' => 'General',
            'settings_whatsapp' => 'WhatsApp',
            'settings_sas' => 'SAS link',
            'settings_templates' => 'Templates',
            'export' => 'Export',
            'import' => 'Import',
            'import_export' => 'Import & Export',
            'print' => 'Print',
            'days_left' => 'Days left',
            'remind_debt' => 'Remind debt',
            'pay_debt' => 'Pay',
            'show_all' => 'Show all',
            'templates' => 'Templates',
            'msg_debt_remind' => 'Debt reminder message',
            'msg_payment_ok' => 'Payment confirmation',
            'msg_debt_created' => 'New debt message',
            'msg_activation' => 'Activation message',
            'partial_pay' => 'Pay amount',
            'remaining_after' => 'Remaining',
            'debt_notes' => 'Debt notes',
            'debt_type_month' => 'Subscription month',
            'debt_type_item' => 'Item / goods',
            'debt_type_month_rent' => 'Subscription month + rent',
            'pay_debts' => 'Pay debts',
            'status_active' => 'Active',
            'status_inactive' => 'Inactive',
            'pay_full' => 'Pay full amount',
            'pay_partial_mode' => 'Pay partial amount',
            'pay_choose_debt' => 'Choose which debt to pay',
            'sub_type' => 'Subscription type',
            'change_sub_type' => 'Change subscription type',
            'select_all' => 'Select all',
            'bulk_activate' => 'Activate selected',
            'operations' => 'Operations',
            'status_active_short' => 'Active',
            'status_expired_short' => 'Expired',
            'status_left_short' => 'Abandoned',
            'confirm_activate' => 'Confirm subscriber activation?',
            'quick_activate' => 'Quick activate',
            'show_details' => 'Show details',
            'hide_details' => 'Hide details',
            'advanced' => 'Advanced',
            'activate_amount' => 'Amount',
            'current_package' => 'Current package',
            'send_message' => 'Send message',
            'send_old_debts_detail' => 'Include old debts in detail',
            'send_wa_notice' => 'Send WhatsApp notice',
            'include_old_debts' => 'Include old debts',
            'old_debts' => 'Old debts',
            'no_old_debts' => 'No old debts',
            'this_activation' => 'This activation',
            'after_activate' => 'After activation',
            'grand_total' => 'Total',
            'pay_this' => 'Pay this',
            'pay_this_amount' => 'Pay this amount',
            'pay_all_debts' => 'Pay all debts',
            'collapse_menu' => 'Collapse menu',
            'collected_chart' => 'Collected this month',
            'activation_sales' => 'Activation sales',
            'sales_short' => 'Sales',
            'activations_month' => 'Activations this month',
            'datetime_card' => 'Date & time',
            'capital' => 'Capital',
            'capital_hint' => 'Cost this month',
            'collected_year' => 'Collected this year',
            'add_debts_tab' => 'Add debts',
            'debts_list_tab' => 'Debts list',
            'debts_need_pay' => 'Debts needing payment',
            'no_debts_now' => 'No debts right now',
            'messages' => 'Messages',
            'clear_data' => 'Clear all data',
            'clear_logs' => 'Clear log',
            'clear_offline' => 'Clear local debts & subscriptions',
            'confirm_clear_logs' => 'This will delete the entire activity log. Sure?',
            'confirm_clear_offline' => 'This will delete local debts, subscriptions and message logs. SAS cache stays. Sure?',
            'select_all' => 'Select all',
            'delete_selected' => 'Delete selected',
            'expire' => 'End',
            'days_unit' => 'days',
            'filter_days' => 'Days left less than or equal',
            'send_filtered' => 'Send to results',
            'send_selected' => 'Send to selected',
            'select_none' => 'Clear selection',
            'msg_mode_debt' => 'Debt reminders',
            'msg_mode_days' => 'Expiring soon',
            'opening_debts' => 'Opening debts',
            'add_debt_line' => 'Add line',
            'remove_debt_line' => 'Remove line',
            'msg_status' => 'Message',
            'msg_history' => 'Message history',
            'retry_send' => 'Retry',
            'confirm_clear' => 'This will delete ALL subscribers, movements and debts. Sure?',
            'choose_month' => 'Choose month',
            'show' => 'Show',
            'custom_text' => 'Custom text',
            'add_debt_btn' => 'Add debt',
            'send_notice' => 'Send notice to subscriber',
        ),
    );
}

function current_lang($settings)
{
    if (!empty($_SESSION['lang'])) {
        return $_SESSION['lang'] === 'en' ? 'en' : 'ar';
    }
    if (!empty($_COOKIE['lang'])) {
        return $_COOKIE['lang'] === 'en' ? 'en' : 'ar';
    }
    return (!empty($settings['language']) && $settings['language'] === 'en') ? 'en' : 'ar';
}

function set_lang_preference($lang)
{
    $lang = ($lang === 'en') ? 'en' : 'ar';
    $_SESSION['lang'] = $lang;
    setcookie('lang', $lang, time() + (365 * 24 * 60 * 60), '/');
    return $lang;
}

function t($key, $lang = null)
{
    static $pack = null;
    if ($pack === null) {
        $pack = lang_all();
    }
    if ($lang === null) {
        $lang = isset($GLOBALS['lang']) ? $GLOBALS['lang'] : 'ar';
    }
    if (isset($pack[$lang][$key])) {
        return $pack[$lang][$key];
    }
    if (isset($pack['ar'][$key])) {
        return $pack['ar'][$key];
    }
    return $key;
}
